#!/bin/bash
IFS=$'\n'
if [ $# -ne 2 ]; then
	echo "usage: ${0##*/} <target> <bucket_name>"
	exit 1;
fi

PROPERTY_FILE=~/.aws_batch/$1
if [ ! -e $PROPERTY_FILE ]; then 
	echo "not exist property file:$PROPERTY_FILE"
	exit 1;
fi

. $PROPERTY_FILE

export AWS_ACCOUNT_NUMBER=$AWS_ACCOUNT_NUMBER
export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
aws s3 --region $AWS_REGION ls s3://$2

