#!/bin/bash
export AWS_ACCOUNT_NUMBER=646774011793
export AWS_ACCESS_KEY_ID='AKIAJPKZUAYRGNBIZS4Q'
export AWS_SECRET_ACCESS_KEY='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'
aws ec2 describe-instances --region 'ap-northeast-1' --output text --query 'Reservations[].Instances[].[PublicIpAddress,Tags[?Key==`Name`].Value|[0]]'

