#!/bin/bash
export AWS_ACCOUNT_NUMBER=232356786261
export AWS_ACCESS_KEY_ID='AKIAJHLRJYTSZZECJ35A'
export AWS_SECRET_ACCESS_KEY='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'
aws ec2 describe-instances --region 'ap-northeast-1' --output text --query 'Reservations[].Instances[].[PublicIpAddress,Tags[?Key==`Name`].Value|[0]]'

