#!/bin/bash
export AWS_ACCESS_KEY_ID='AKIAJSYK7W63CSNJFHZA'
export AWS_SECRET_ACCESS_KEY='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'
aws ec2 describe-instances --region 'ap-northeast-1' --output text --query 'Reservations[].Instances[].[PublicIpAddress,Tags[?Key==`Name`].Value|[0]]'

