#!/bin/bash -x
IFS=$'\n'
PROPERTY_FILE=~/.aws_batch/.slack2
if [ ! -e $PROPERTY_FILE ]; then 
	echo "not exist property file:$PROPERTY_FILE"
	exit 1;
fi

. $PROPERTY_FILE

text=""
aws_team_list=(
"tfhd"
"firstship"
"tonoel"
"dear"
"hakuba"
"iwatake"
)
for aws_team in ${aws_team_list[@]}
do
	text=$text""
	for line in `aws_cw_get_transfer ${aws_team}`
	do
		text=$text$line"\n"
	done
	text=$text"--------------\n"
done
echo $slack_webhook_url
text="\`\`\`\n"$text"\n\`\`\`"
echo -e $text

#exit;

curl -s -S -X POST --data-urlencode "payload={ \
    \"channel\": \"${slack_channel}\", \
    \"username\": \"${slack_botname}\", \
    \"text\": \"${text}\" \
    }" ${slack_webhook_url} >/dev/null

